### PR TITLE
Feature/add py37 dict

### PR DESCRIPTION
**Pull request by mayou36**
Add functionality for python 3.7 to store dicts and load as dicts (as they are [ordered](https://www.blog.pythonlibrary.org/2018/02/27/python-3-7-dictionaries-now-ordered/)).

---
This change is [Reviewable](https://reviewable.io/reviews/phynix/yamlloader/14)

### CODE REVIEW

**Comment by SebastianJL** [comment]
Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---

*[.scrutinizer.yml, line 7 at r1](https://reviewable.io/reviews/phynix/yamlloader/14#-LE_zuMc0TPATxicLyic:-LE_zuMc0TPATxicLyid:b7atu2z) ([raw file](https://github.com/phynix/yamlloader/blob/dd84ff998137c141c66446ed0befb48d3ebcd7f1/.scrutinizer.yml#L7)):*
> ```YAML
> build:
>     environment:
>         python: '3.6.3'
> ```

Shouldn't there also be python 3.7 as this pull request adds support for ordered dicts in python 3.7?

---

*[yamlloader/settings.py, line 13 at r1](https://reviewable.io/reviews/phynix/yamlloader/14#-LE_z_y81X2eKytqDCiR:-LE_z_y81X2eKytqDCiS:b72illj) ([raw file](https://github.com/phynix/yamlloader/blob/dd84ff998137c141c66446ed0befb48d3ebcd7f1/yamlloader/settings.py#L13)):*
> ```Python
> ALLOW_NON_C_FALLBACK = True
> 
> PY_GE_37 = sys.version_info[:2] >= (3, 7)
> ```

PY_GE_37 does not follow the same naming convention as pyle36. I prefer the first one and would advise to change all ocurences of pyle36 to PY_LE_36

---

*[yamlloader/ordereddict/dumpers.py, line 15 at r1](https://reviewable.io/reviews/phynix/yamlloader/14#-LEa-I8-A1dccCqbU526:-LEa-I8-A1dccCqbU527:b-kcqvbb) ([raw file](https://github.com/phynix/yamlloader/blob/dd84ff998137c141c66446ed0befb48d3ebcd7f1/yamlloader/ordereddict/dumpers.py#L15)):*
> ```Python
> 
> def represent_ordereddict(self, data):
>     """
> ```

We could  use type hints instead.

---

*[yamlloader/ordereddict/dumpers.py, line 41 at r1](https://reviewable.io/reviews/phynix/yamlloader/14#-LEa-VKf8HsZUkOKjSR4:-LEa-VKf8HsZUkOKjSR5:b-quwhay) ([raw file](https://github.com/phynix/yamlloader/blob/dd84ff998137c141c66446ed0befb48d3ebcd7f1/yamlloader/ordereddict/dumpers.py#L41)):*
> ```Python
>             self.add_representer(dict, type(self).represent_ordereddict)
> 
>     represent_ordereddict = represent_ordereddict
> ```

Is this really correct? Seems unnecessary.

---


*Comments from [Reviewable](https://reviewable.io/reviews/phynix/yamlloader/14)*

**Comment by SebastianJL** [comment]
Reviewed 5 of 8 files at r1.
Review status: 5 of 8 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/phynix/yamlloader/14)*

**Comment by mayou36** [comment]
*[.scrutinizer.yml, line 7 at r1](https://reviewable.io/reviews/phynix/yamlloader/14#-LE_zuMc0TPATxicLyic:-LEa2bps3WwVdAcxMawz:b-6lfq9h) ([raw file](https://github.com/phynix/yamlloader/blob/dd84ff998137c141c66446ed0befb48d3ebcd7f1/.scrutinizer.yml#L7)):*
<details><summary><i>Previously, SebastianJL wrote…</i></summary><blockquote>

Shouldn't there also be python 3.7 as this pull request adds support for ordered dicts in python 3.7?
</blockquote></details>

Not really, as scrutinizer is not used as the CI, rather travis is. So "any" version will do, but can be changed in the future to 3.7 of course!

---


*Comments from [Reviewable](https://reviewable.io/reviews/phynix/yamlloader/14)*

**Comment by mayou36** [comment]
Review status: 5 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[yamlloader/settings.py, line 13 at r1](https://reviewable.io/reviews/phynix/yamlloader/14#-LE_z_y81X2eKytqDCiR:-LEa479M82lE_eY6yqMg:b-1jbndn) ([raw file](https://github.com/phynix/yamlloader/blob/dd84ff998137c141c66446ed0befb48d3ebcd7f1/yamlloader/settings.py#L13)):*
<details><summary><i>Previously, SebastianJL wrote…</i></summary><blockquote>

PY_GE_37 does not follow the same naming convention as pyle36. I prefer the first one and would advise to change all ocurences of pyle36 to PY_LE_36
</blockquote></details>

Agree!

Done!

---

*[yamlloader/ordereddict/dumpers.py, line 15 at r1](https://reviewable.io/reviews/phynix/yamlloader/14#-LEa-I8-A1dccCqbU526:-LEa4SkQ02FwM2Ovv7Se:b-n9ye7h) ([raw file](https://github.com/phynix/yamlloader/blob/dd84ff998137c141c66446ed0befb48d3ebcd7f1/yamlloader/ordereddict/dumpers.py#L15)):*
<details><summary><i>Previously, SebastianJL wrote…</i></summary><blockquote>

We could  use type hints instead.
</blockquote></details>

Not really, compatibility... (here we have, against all odds but realistically, still 2.7 on board... which is I think the main reason I created an extra repository back then)

---

*[yamlloader/ordereddict/dumpers.py, line 41 at r1](https://reviewable.io/reviews/phynix/yamlloader/14#-LEa-VKf8HsZUkOKjSR4:-LEa5iyn9ooqLM1dNAua:b-342rr9) ([raw file](https://github.com/phynix/yamlloader/blob/dd84ff998137c141c66446ed0befb48d3ebcd7f1/yamlloader/ordereddict/dumpers.py#L41)):*
<details><summary><i>Previously, SebastianJL wrote…</i></summary><blockquote>

Is this really correct? Seems unnecessary.
</blockquote></details>

It's correct. We're inside the class body, so it's a way of assigning a static method. Although, I agree, a slightly odd one... 

---


*Comments from [Reviewable](https://reviewable.io/reviews/phynix/yamlloader/14)*

**Comment by mayou36** [comment]
Review status: 3 of 8 files reviewed, 4 unresolved discussions (waiting on @SebastianJL)

---

*[yamlloader/settings.py, line 13 at r1](https://reviewable.io/reviews/phynix/yamlloader/14#-LE_z_y81X2eKytqDCiR:-LEkr6lF93aDITjb4a6A:b-896fix) ([raw file](https://github.com/phynix/yamlloader/blob/dd84ff998137c141c66446ed0befb48d3ebcd7f1/yamlloader/settings.py#L13)):*
<details><summary><i>Previously, mayou36 (Jonas Eschle) wrote…</i></summary><blockquote>

Agree!

Done!
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/phynix/yamlloader/14)*

**Comment by SebastianJL** [comment]
Reviewed 1 of 8 files at r1, 6 of 7 files at r2.
Review status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @SebastianJL)

---

*[yamlloader/ordereddict/dumpers.py, line 41 at r1](https://reviewable.io/reviews/phynix/yamlloader/14#-LEa-VKf8HsZUkOKjSR4:-LGOy-x02TB9I0YrxFs6:bgk3mqm) ([raw file](https://github.com/phynix/yamlloader/blob/dd84ff998137c141c66446ed0befb48d3ebcd7f1/yamlloader/ordereddict/dumpers.py#L41)):*
<details><summary><i>Previously, mayou36 (Jonas Eschle) wrote…</i></summary><blockquote>

It's correct. We're inside the class body, so it's a way of assigning a static method. Although, I agree, a slightly odd one... 
</blockquote></details>

Ok thanks. Maybe you want to consider adding the staticmethod wrapper then. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/phynix/yamlloader/14)*

**Comment by mayou36** [comment]
CI for 3.7 finally passes. Ready to merge from my side, what do you think @SebastianJL ?

**Pull request merged**
